### ISSUE TITLE
Revision for map byte $314: Apply double damage per family member

### ISSUE THREAD

**Issue by tbveralrud** [bbbradsmith/lotwtool#2]
Map byte $314 is a bitfield that dictates if the room will deal double damage to the player or not. This feature is used to discourage a family member from traversing to where they are not intended to venture.

I verified this by setting a map's bitfield at this address from $1F (1x damage to all family members) to 0 (2x damage to all).

More info at [LDS4 / Conditions for x2 the STR of a monster](http://lsd4.starfree.jp/glitch/#monster_double_damage). (Not my site.)

**Comment by bbbradsmith** [comment]
Do you know if this applies to all 4 versions, or is it just for NES/Famicom?

**Comment by tbveralrud** [comment]
According to the link I posted it is a feature in all versions; "(ALL ver)" being in the title of the section.

I have not verified this claim.

**Comment by bbbradsmith** [comment]
okay I've updated the descriptions now
